name: Backend Release Distribution 

on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Backend Repository
      uses: actions/checkout@v4
      with:
        repository: SwissGacho/Haushaltbuch
        ref: release
        path: backend

    - name: Checkout Dist Repository
      uses: actions/checkout@v4
      with:
        repository: SwissGacho/Dist
        ssh-key: ${{secrets.DIST}}
        ref: main
        path: dist
    - name: Copy backend to dist repo
      run: |
        ls -R dist
        find dist/moneypilot/* -maxdepth 0 ! -name frontend -exec rm -rf {} \;
        cp -r backend/backend/src/* dist/moneypilot
    - name: Commit to Dist repo
      working-directory: dist
      run: |
        git config --global user.email "backend@github.com"
        git config --global user.name "Gacho BE"
        git add .
        git commit -m 'New backend commit'
        git push


