name: Zweiter Workflow 

on:
  push:
    branches:
      # - main  # Branch, auf dem der Workflow ausgelöst wird
      - 55-create-dist-workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo Hallo Velo
      run: echo Hallo Velo
